---
- name: Install codex (linux)
  become: true
  community.general.npm:
    name: "@openai/codex"
    unsafe_perm: true
    global: true
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install codex (macos)
  community.general.homebrew_cask:
    name: codex
    install_options: appdir=/Applications
    state: latest
  when: ansible_distribution == 'MacOSX'
