---
- name: Install logitech driver (linux)
  become: true
  ansible.builtin.apt:
    name: logiops
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install logitech driver (macos)
  community.general.homebrew_cask:
    name: logi-options-plus
    install_options: appdir=/Applications
    state: latest
  when: ansible_distribution == 'MacOSX'
