---
browser:
  default: brave-browser

config:
  repository: https://github.com/tomdewildt/config.git
  timezone: Europe/Amsterdam

code:
  extensions:
    # AI
    - github.copilot
    # Ansible
    - redhat.ansible
    # Docker
    - ms-azuretools.vscode-docker
    # Dotenv
    - mikestead.dotenv
    # General
    - arcticicestudio.nord-visual-studio-code
    - mechatroner.rainbow-csv
    - ms-vsliveshare.vsliveshare
    # Golang
    - golang.go
    # HCL
    - hashicorp.hcl
    # Javascript
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - vitest.explorer
    # Jupyter
    - ms-toolsai.jupyter
    # Markdown
    - yzhang.markdown-all-in-one
    # Python
    - ms-python.python
    - ms-python.vscode-pylance
    - teticio.python-envy
    # Spellcheck
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-dutch
    # Terraform
    - hashicorp.terraform
    # TOML
    - tamasfe.even-better-toml
    # YAML
    - redhat.vscode-yaml

golang:
  version: 1.21.4

node:
  version: 22.x
  packages:
    - cdktf-cli
    - gatsby-cli

python:
  version: 3.11.14
  packages:
    - ruff
    - pyright
    - virtualenv

vagrant:
  version: 2.4.0
