---
- name: Install maps (linux)
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  block:
    - name: Read browser desktop file (linux)
      ansible.builtin.slurp:
        src: /usr/share/applications/{{ browser.default }}.desktop
      register: browser_file

    - name: Extract browser executable (linux)
      ansible.builtin.set_fact:
        browser_executable: "{{ browser_file.content | b64decode | regex_search('^Exec=([^ ]*).*', '\\1', multiline=True) | first }}"

    - name: Ensure icons folder exists (linux)
      ansible.builtin.file:
        path: /usr/share/applications/icons
        state: directory
        mode: "0755"

    - name: Download maps icon (linux)
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/google-maps.png
        dest: /usr/share/applications/icons/google-maps.png
        owner: root
        group: root
        mode: "0644"

    - name: Copy maps desktop file (linux)
      ansible.builtin.template:
        src: templates/maps/maps.desktop.j2
        dest: /usr/share/applications/google-maps.desktop
        owner: root
        group: root
        mode: "0644"
# TODO: install maps (macos)
