---
- name: Install gcp cli (linux)
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  block:
    - name: Add gcp cli repository (linux)
      ansible.builtin.deb822_repository:
        name: google-cloud
        types: [deb]
        uris: [https://packages.cloud.google.com/apt]
        suites: [cloud-sdk]
        components: [main]
        architectures: [amd64]
        signed_by: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Install gcp cli (linux)
      ansible.builtin.apt:
        name: google-cloud-sdk
        update_cache: true
        state: latest

- name: Install gcp cli (macos)
  community.general.homebrew_cask:
    name: google-cloud-sdk
    install_options: appdir=/Applications
    state: latest
  when: ansible_distribution == 'MacOSX'
