---
- name: Install azure cli (linux)
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  block:
    - name: Add azure cli repository (linux)
      ansible.builtin.deb822_repository:
        name: azure
        types: [deb]
        uris: [https://packages.microsoft.com/repos/azure-cli/]
        suites: [bookworm]
        components: [main]
        architectures: [amd64]
        signed_by: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Install azure cli (linux)
      ansible.builtin.apt:
        name: azure-cli
        update_cache: true
        state: latest

- name: Install azure cli (macos)
  community.general.homebrew:
    name: azure-cli
    state: latest
  when: ansible_distribution == 'MacOSX'
