---
- name: Install ffmpeg (linux)
  become: true
  ansible.builtin.apt:
    name: ffmpeg
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install ffmpeg (macos)
  community.general.homebrew:
    name: ffmpeg
    state: latest
  when: ansible_distribution == 'MacOSX'
