---
- name: Install fzf (linux)
  become: true
  ansible.builtin.apt:
    name: fzf
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install fzf (macos)
  community.general.homebrew:
    name: fzf
    state: latest
  when: ansible_distribution == 'MacOSX'
