---
- name: Install sound recorder (linux)
  become: true
  ansible.builtin.apt:
    name: gnome-sound-recorder
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
