---
- name: Install font viewer (linux)
  become: true
  ansible.builtin.apt:
    name: gnome-font-viewer
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
