---
- name: Install system monitor (linux)
  become: true
  ansible.builtin.apt:
    name: gnome-system-monitor
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
